const images = [{
        id: 23,
        thumb: '/nugsimages/nugstgal23.jpeg',
        src: '/nugsimages/nugstgal23.jpeg',
        caption: '<h4>The Nugs-T registration card</h4>',
    },
    {
        id: 22,
        thumb: '/nugsimages/nugstgal22.jpeg',
        src: '/nugsimages/nugstgal22.jpeg',
        caption: '<h4>Heallth Screening 16 July 2019</h4>',
    },
    {
        id: 21,
        thumb: '/nugsimages/nugstgal21.jpeg',
        src: '/nugsimages/nugstgal21.jpeg',
        caption: '<h4>New vice president at the inauguration</h4>',
    },
    {
        id: 20,
        thumb: '/nugsimages/nugstgal20.jpeg',
        src: '/nugsimages/nugstgal20.jpeg',
        caption: '<h4>New President & vice president at the inauguration</h4>',
    },
    {
        id: 19,
        thumb: '/nugsimages/nugstgal19.jpeg',
        src: '/nugsimages/nugstgal19.jpeg',
        caption: '<h4>Swearing in of the Vice president</h4>',
    },
    {
        id: 18,
        thumb: '/nugsimages/nugstgal18.jpeg',
        src: '/nugsimages/nugstgal18.jpeg',
        caption: '<h4>Outgoing president and Incoming President</h4>',
    },
    {
        id: 17,
        thumb: '/nugsimages/nugstgal17.jpeg',
        src: '/nugsimages/nugstgal17.jpeg',
        caption: '<h4>Outgoing and Incoming top executives with vice dean Elena</h4>',
    },
    {
        id: 16,
        thumb: '/nugsimages/nugstgal16.jpeg',
        src: '/nugsimages/nugstgal16.jpeg',
        caption: '<h4>New executives at the inauguration</h4>',
    },
    {
        id: 15,
        thumb: '/nugsimages/nugstgal15.jpeg',
        src: '/nugsimages/nugstgal15.jpeg',
        caption: '<h4>New president and vice with With Mr Samuel</h4>',
    },
    {
        id: 14,
        thumb: '/nugsimages/nugstgal14.jpeg',
        src: '/nugsimages/nugstgal14.jpeg',
        caption: '<h4>Heallth Screening 16 July 2019</h4>',
    },
    {
        id: 13,
        thumb: '/nugsimages/nugstgal13.jpeg',
        src: '/nugsimages/nugstgal13.jpeg',
        caption: '<h4>Heallth Screening 16 July 2019</h4>',
    },
    {
        id: 12,
        thumb: '/nugsimages/nugstgal12.jpeg',
        src: '/nugsimages/nugstgal12.jpeg',
        caption: '<h4>Heallth Screening 16 July 2019</h4>',
    },
    {
        id: 11,
        thumb: '/nugsimages/nugstgal11.jpeg',
        src: '/nugsimages/nugstgal11.jpeg',
        caption: '<h4>Heallth Screening 16 July 2019</h4>',
    },
    {
        id: 10,
        thumb: '/nugsimages/nugstgal10.jpeg',
        src: '/nugsimages/nugstgal10.jpeg',
        caption: '<h4>Heallth Screening 16 July 2019</h4>',
    },
    {
        id: 9,
        thumb: '/nugsimages/nugstgal9.jpeg',
        src: '/nugsimages/nugstgal9.jpeg',
        caption: '<h4>Heallth Screening 16 July 2019</h4>',
    },
    {
        id: 8,
        thumb: '/nugsimages/nugstgal8.jpeg',
        src: '/nugsimages/nugstgal8.jpeg',
        caption: '<h4>Heallth Screening 16 July 2019</h4>',
    },
    {
        id: 7,
        thumb: '/nugsimages/nugstgal7.jpeg',
        src: '/nugsimages/nugstgal7.jpeg',
        caption: '<h4>President and Vice with Vice deans</h4>',
    },
    {
        id: 6,
        thumb: '/nugsimages/nugstgal6.jpeg',
        src: '/nugsimages/nugstgal6.jpeg',
        caption: '<h4>Executives for the 2019/2020 session on inauguration day.</h4>',
    },
    {
        id: 5,
        thumb: '/nugsimages/nugstgal5.jpeg',
        src: '/nugsimages/nugstgal5.jpeg',
        caption: '<h4>NugsT President 2019/2020 with the Rector of TNMU</h4>',
    },
    {
        id: 4,
        thumb: '/nugsimages/nugstgal4.jpeg',
        src: '/nugsimages/nugstgal4.jpeg',
        caption: '<h4>President and Vice with Vice dean Mr Furdela</h4>',
    },
    {
        id: 3,
        thumb: '/nugsimages/nugstgal3.jpeg',
        src: '/nugsimages/nugstgal3.jpeg',
        caption: '<h4>NugsT executives 2019/2020 with TNMU Dean and vice deans.</h4>',
    },
    {
        id: 2,
        thumb: '/nugsimages/nugstgal2.jpeg',
        src: '/nugsimages/nugstgal2.jpeg',
        caption: '<h4>NugsT President 2019/2020 with the Rector of TNMU</h4>',
    },
    {
        id: 1,
        thumb: '/nugsimages/nugstgal1.jpeg',
        src: '/nugsimages/nugstgal1.jpeg',
        caption: '<h4>Female executives with the Vice deans.</h4>',
    },
]

export default images